### PR TITLE
Organize Capabilities in app.cc

### PR DESCRIPTION
**Pull request by WildByDesign**
Organize capabilities, make Basic and LPAC capabilities easy to select and add additional Named Capabilities.

### CODE REVIEW

**Comment by WildByDesign** [comment]
Please review and see if this organization of capabilities is OK. Thank you.

**Comment by fcharlie** [comment]
Good, but I have a question, whether you are building the test locally, whether the ListView layout needs to be modified, (some Capability display names may be too long).

If you run OK, you can post a screenshot

Thanks.

**Comment by WildByDesign** [comment]
Yes, I have compiled this locally and have been using successfully for several hours today.  Also, the pull request has triggered an AppVeyor build to compile which I thought was quite interesting. I would suggest to grab that latest Appveyor build because that will show better than a screenshot.

https://ci.appveyor.com/project/fcharlie/privexec/build/artifacts

ListView did not need any changes. Everything fits well horizontally without clipping off any text. I used simple spaces to assist with sorting the list so that the Well Known SIDs and LPAC were at the top of the list.

I would suggest to grab the latest build from AppVeyor that was trigger and play with that a bit to see if you like the changes or not. After some testing, please let me know if it is OK or not. Thank you.

**Comment by fcharlie** [comment]
@WildByDesign OK I will test it.

**Pull request merged**
